import type { LogicEdge, LogicNode, LogicTrailGraph } from "../graph/model.js";

const MAX_STEPS = 30;

/**
 * Writes a plain-language walkthrough of a flow from its structure alone.
 * Used when no LLM is configured; every statement maps to an edge in the graph.
 */
export function narrateFlow(graph: LogicTrailGraph): string {
  const nodes = new Map(graph.nodes.map((node) => [node.id, node]));
  const outgoing = new Map<string, LogicEdge[]>();
  for (const edge of graph.edges) {
    (outgoing.get(edge.from) ?? outgoing.set(edge.from, []).get(edge.from))?.push(edge);
  }
  if (graph.nodes.length === 0) return "No relevant code was found for this question.";

  const lines: string[] = [];
  const entries = graph.entryPoints.flatMap((id) => nodes.get(id) ?? []);
  if (entries.length > 0) {
    lines.push(
      `The flow starts at ${entries.map((node) => `${code(node.label)}${location(node)}`).join(" and ")}.`,
    );
  }

  const order: LogicNode[] = [];
  const seen = new Set<string>();
  const queue = [...graph.entryPoints];
  while (queue.length > 0) {
    const id = queue.shift();
    if (id === undefined || seen.has(id)) continue;
    seen.add(id);
    const node = nodes.get(id);
    if (!node) continue;
    order.push(node);
    for (const edge of outgoing.get(id) ?? []) queue.push(edge.to);
  }
  for (const node of graph.nodes) if (!seen.has(node.id)) order.push(node);

  const incomingFrom = new Map<string, string[]>();
  for (const edge of graph.edges) {
    (incomingFrom.get(edge.to) ?? incomingFrom.set(edge.to, []).get(edge.to))?.push(edge.from);
  }
  const steps: string[] = [];
  for (const node of order) {
    if (node.type === "condition") {
      // Top-level conditions are described inline by their owner; nested ones get their own step.
      const parents = incomingFrom.get(node.id) ?? [];
      if (parents.some((id) => nodes.get(id)?.type === "condition")) {
        steps.push(`If ${code(node.label)}: ${describeArms(node, outgoing, nodes)}.`);
      }
    } else {
      const clauses = describeOutgoing(node, outgoing, nodes);
      if (clauses.length > 0) steps.push(`${code(node.label)} ${clauses.join("; ")}.`);
    }
    if (steps.length >= MAX_STEPS) break;
  }
  if (steps.length > 0) {
    lines.push("");
    steps.forEach((step, index) => lines.push(`${index + 1}. ${step}`));
  }

  const inferred = graph.edges.filter((edge) => edge.source === "inferred");
  lines.push("");
  lines.push(
    "Generated by static analysis without an LLM: descriptions come from doc comments and code facts." +
      (inferred.length > 0
        ? " Steps marked (inferred) are likely but not proven by a call site."
        : ""),
  );
  return lines.join("\n");
}

function describeOutgoing(
  node: LogicNode,
  outgoing: ReadonlyMap<string, LogicEdge[]>,
  nodes: ReadonlyMap<string, LogicNode>,
): string[] {
  // Clauses keep the order in which their first edge appears (source-code order).
  const clauses = new Map<string, { verb: string; targets: string[] } | string>();
  const add = (verb: string, text: string): void => {
    const existing = clauses.get(verb);
    if (typeof existing === "object") {
      if (!existing.targets.includes(text)) existing.targets.push(text);
    } else {
      clauses.set(verb, { verb, targets: [text] });
    }
  };
  for (const edge of outgoing.get(node.id) ?? []) {
    const target = nodes.get(edge.to);
    if (!target) continue;
    const name = code(target.label) + (edge.source === "inferred" ? " (inferred)" : "");
    if (target.type === "condition") {
      clauses.set(`condition:${target.id}`, describeCondition(target, outgoing, nodes));
      continue;
    }
    switch (edge.type) {
      case "calls":
        if (edge.label === "middleware") add("runs middleware", name);
        else
          add("calls", edge.label && edge.label !== "for each" ? `${name} on ${edge.label}` : name);
        break;
      case "renders":
        add("renders", name);
        break;
      case "requests":
        add("sends", name);
        break;
      case "reads":
        add("reads", name);
        break;
      case "writes":
        add("writes", name);
        break;
      case "emits":
        add("emits", name);
        break;
      case "triggers":
        add(target.type === "route" ? "leads to" : "triggers", name);
        break;
      case "navigates":
        add("navigates to", name.replace(/^`navigate /, "`"));
        break;
      case "returns":
        add("returns", name);
        break;
      case "condition":
        break;
    }
  }
  return [...clauses.values()].map((clause) =>
    typeof clause === "string" ? clause : `${clause.verb} ${joinList(clause.targets)}`,
  );
}

function describeCondition(
  condition: LogicNode,
  outgoing: ReadonlyMap<string, LogicEdge[]>,
  nodes: ReadonlyMap<string, LogicNode>,
): string {
  const isCatch = condition.metadata?.kind === "catch";
  const arms = describeArms(condition, outgoing, nodes);
  return isCatch
    ? `on error: ${arms.replace(/^error → /, "")}`
    : `checks ${code(condition.label)} (${arms})`;
}

function describeArms(
  condition: LogicNode,
  outgoing: ReadonlyMap<string, LogicEdge[]>,
  nodes: ReadonlyMap<string, LogicNode>,
): string {
  const arms = new Map<string, string[]>();
  for (const edge of outgoing.get(condition.id) ?? []) {
    const target = nodes.get(edge.to);
    if (!target) continue;
    const arm = edge.branch ?? "then";
    const list = arms.get(arm) ?? [];
    list.push(target.type === "condition" ? `checks ${code(target.label)}` : code(target.label));
    arms.set(arm, list);
  }
  return [...arms].map(([arm, targets]) => `${arm} → ${targets.join(", ")}`).join("; ");
}

function code(text: string): string {
  return `\`${text}\``;
}

function location(node: LogicNode): string {
  return node.file ? ` (${node.file}${node.line ? `:${node.line}` : ""})` : "";
}

function joinList(items: readonly string[]): string {
  if (items.length <= 1) return items.join("");
  return `${items.slice(0, -1).join(", ")} and ${items[items.length - 1]}`;
}
